import Rsa.*;
import MREA.*;
import Jnssql.*;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.StandardEntityCollection;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wilson
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
      
        getContentPane().setBackground(Color.WHITE);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plain Text             ::");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 130, 149, 34);

        jButton1.setText("RSA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 530, 110, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 140, 209, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 220, 378, 45);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 290, 209, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Encrypted Text   ::");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 220, 149, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Decrypted Text   ::");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 290, 149, 28);

        jButton2.setText("Clear Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 620, 100, 34);

        jButton3.setText("MREA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 531, 120, 40);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(140, 440, 96, 29);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(340, 440, 98, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Encryption ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 370, 116, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time ::");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 370, 116, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Key Generation");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(540, 370, 116, 28);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(1027, 0, 18, 258);

        jButton7.setText("Browse");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(690, 140, 110, 30);

        jButton8.setText("Encryption");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1010, 400, 100, 30);

        jButton9.setText("Decryption");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1120, 400, 100, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20150417_090611.JPG"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 0, 150, 120);

        jButton4.setText("JNS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(810, 480, 110, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00000000", "00000001", "00000010", "00000011", "00001001", "00001010", "00001011", "00001100", "00001101", "00001110", "00001111", "00010000", "00010001", "00010010", "00010011" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(870, 430, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":: Statistics ::");
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 25));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1060, 340, 100, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":: JNS Algo ::");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(820, 380, 90, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Nid ::");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(760, 430, 100, 17);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (2).jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(750, 360, 220, 230);

        jButton6.setText("Decryption ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1120, 220, 100, 23);

        jButton10.setText("Clear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(470, 140, 70, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(360, 440, 98, 29);

        jButton5.setText("Encryption");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1010, 220, 90, 23);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(540, 440, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Generate Graph for ::");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1040, 160, 170, 28);

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (2).jpg"))); // NOI18N
        jLabel15.setText("jLabel12");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1000, 330, 230, 130);

        jLabel16.setBackground(new java.awt.Color(255, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (2).jpg"))); // NOI18N
        jLabel16.setText("jLabel12");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1000, 140, 230, 130);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Decryption");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(340, 370, 116, 28);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue-curves-.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -50, 1360, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        dataset.setValue(ETime1,"TIME","RSA");
        dataset.setValue(ETime2,"TIME","MREA");
        dataset.setValue(ETime3,"TIME","JNS");
        JFreeChart chart = ChartFactory.createBarChart3D("Encryption", "Algorithms", "Time", dataset, PlotOrientation.VERTICAL, false, true, false);
        //chart.setBackgroundPaint(Color.black);
        chart.getTitle().setPaint(Color.BLACK);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);

        //JFreeChart charts= ChartFactory.

        ChartFrame frame=new ChartFrame("Comparition Between Algorithms",chart);

        frame.setVisible(true);
        frame.setSize(550,450);

        try{
            final ChartRenderingInfo info= new ChartRenderingInfo(new StandardEntityCollection());
            final File file1=new File("EncryptionChart.png");
            ChartUtilities.saveChartAsJPEG(file1, chart, 600, 400);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultCategoryDataset dataset1=new DefaultCategoryDataset();
        dataset1.setValue(DTime1,"TIME","RSA");
        dataset1.setValue(DTime2,"TIME","MREA");
        dataset1.setValue(DTime3,"TIME","JNS");
        JFreeChart chart1 = ChartFactory.createBarChart3D("Decryption", "Algorithms", "Time", dataset1, PlotOrientation.VERTICAL, false, true, false);
        ChartFrame frame1=new ChartFrame("Comparition Between Algorithms",chart1);
        frame1.setVisible(true);
        frame1.setSize(550,450);//chart.setBackgroundPaint(Color.black); // TODO add your handling code here:

        try{
            final ChartRenderingInfo info= new ChartRenderingInfo(new StandardEntityCollection());
            final File file1=new File("DecryptionChart.png");
            ChartUtilities.saveChartAsJPEG(file1, chart1, 600, 400);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     // NewJFrame j=new NewJFrame();
     //   j.jButton2ActionPerformed(java.awt.event.ActionEvent evt);// TODO add your handling code here:
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        System.out.println("what the ffff");
        String h[] = null;

        String g[]=null;
        Jnssql s=new Jnssql();
        try {

            String n=jComboBox1.getSelectedItem().toString();
          // long startTime = System.currentTimeMillis();
            h= s.Run1(jTextField1.getText(),n);
            jTextField2.setText(h[0]);
            ETime3=Long.valueOf(h[1]);
            jTextField4.setText(h[1]);
          //  long stopTime = System.currentTimeMillis();
           // ETime3 = stopTime - startTime;
          //  jTextField4.setText(String.valueOf(ETime1));
 jTextField3.setText(String.valueOf(h[2]));
           // DTime1 = Math.abs((stopTime - startTime)-ETime1);
            DTime3=Long.valueOf(h[3]);
            jTextField5.setText(h[3]);
              jTextField7.setText("0");
           /* //startTime = System.currentTimeMillis();
            g= s.Run2(jTextField1.getText(),n);
            //stopTime = System.currentTimeMillis();
            jTextField3.setText(String.valueOf(g[0]));
           // DTime1 = Math.abs((stopTime - startTime)-ETime1);
            DTime3=Long.valueOf(g[1]);
            jTextField5.setText(g[1]);*/

        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        String h[] = null;

     //   String g[]=null;
        MREA a=new MREA();
        String p=jTextField1.getText();
        
        
            try{
               // long startTime = System.currentTimeMillis();
                h= a.Run1(jTextField1.getText());
                jTextField2.setText(h[0]);
              //  long stopTime = System.currentTimeMillis();
               ETime2=Long.valueOf(h[1]);
                jTextField4.setText(h[1]);

                jTextField3.setText(String.valueOf(h[2]));
              //  DTime2 = Math.abs((stopTime - startTime)-ETime2);
                 DTime2=Long.valueOf(h[3]);
                jTextField5.setText(h[3]);
                  jTextField7.setText(h[4]);
             /*  // startTime = System.currentTimeMillis();
                g= a.Run2(jTextField1.getText());
               // stopTime = System.currentTimeMillis();
                jTextField3.setText(String.valueOf(g[0]));
              //  DTime2 = Math.abs((stopTime - startTime)-ETime2);
                 DTime2=Long.valueOf(g[1]);
                jTextField5.setText(g[1]);*/

            }
            catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            

            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
         jTextField7.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        String[] h = null;
       // String[] g=null;

        Rsa a=new Rsa();
        try {
          //  long startTime = System.currentTimeMillis();
            h= a.Run1(jTextField1.getText());
            jTextField2.setText(h[0]);
            ETime1=Long.valueOf(h[1]);
            jTextField4.setText(h[1]);
             jTextField3.setText(String.valueOf(h[2]));
            DTime1=Long.valueOf(h[3]);
            jTextField5.setText(h[3]);
            
          //   KTime1=Long.valueOf(h[4]);
            jTextField7.setText(h[4]);
          //  long stopTime = System.currentTimeMillis();
         //   ETime1 = stopTime - startTime;
          //  jTextField4.setText(String.valueOf(ETime1));

            //startTime = System.currentTimeMillis();
          /*  g= a.Run2(jTextField1.getText());
            //stopTime = System.currentTimeMillis();
            jTextField3.setText(String.valueOf(g[0]));
           // DTime1 = Math.abs((stopTime - startTime)-ETime1);
            DTime1=Long.valueOf(g[1]);
            jTextField5.setText(g[1]);*/
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 JFileChooser chooser= new JFileChooser();
       chooser.showOpenDialog(null);
       File f=chooser.getSelectedFile();
       String i=null;
          try {

        Scanner sc = new Scanner(f);

        while (sc.hasNextLine()) {
            i = sc.nextLine();
            
        }
        sc.close();
    } 
    catch (Exception e) {
        
    }
 
       
       jTextField1.setText(i);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
          String rsa = "RSA";
      String mrea = "MREA";
     String jns = "JNS";
    String one = "1 Kb";
      String two = "2 Kb";
      String three = "3 Kb";
       String four = "4 Kb";
       String five = "5 Kb";
       String six = "6 Kb";
       String seven = "7 Kb";
       String eight = "8 Kb";

      DefaultCategoryDataset dataset = new DefaultCategoryDataset( );

      dataset.addValue( 68.0 , rsa , one );
      dataset.addValue( 75.0 , rsa , two );
      dataset.addValue( 100.0 , rsa , three );
      dataset.addValue(110.0 , rsa , four );
      dataset.addValue( 122.0 , rsa , five );
      dataset.addValue( 128.0 , rsa , six );
      dataset.addValue( 135.0 , rsa , seven );
      dataset.addValue( 141.0 , rsa , eight );

      dataset.addValue( 393.0 , mrea , one );
      dataset.addValue( 402.0 , mrea ,two );
      dataset.addValue( 411.0 , mrea , three );
      dataset.addValue( 413.0 , mrea , four );
      dataset.addValue( 421.0 , mrea , five );
      dataset.addValue( 457.0 , mrea , six );
      dataset.addValue( 501.0 , mrea , seven );
      dataset.addValue( 514.0 , mrea , eight );

      dataset.addValue( 40.0 , jns , one );
      dataset.addValue( 51.0 , jns , two );
      dataset.addValue( 65.0 , jns , three );
      dataset.addValue( 73.0 , jns , four );
       dataset.addValue( 86.0 , jns , five );
        dataset.addValue( 89.0 , jns , six );
         dataset.addValue( 98.0 , jns , seven );
          dataset.addValue( 110.0 , jns , eight );

      JFreeChart barChart = ChartFactory.createBarChart(
         "Encryption Comparison", 
         "Algorithm", "Time", 
         dataset,PlotOrientation.VERTICAL, 
         true, true, false);
          ChartFrame frame1=new ChartFrame("Comparison Between Algorithms",barChart);
        frame1.setVisible(true);
        frame1.setSize(950,450);
      int width = 640; /* Width of the image */
      int height = 480; /* Height of the image */ 
       try{
            final ChartRenderingInfo info= new ChartRenderingInfo(new StandardEntityCollection());
            final File file1=new File("EncryptionKBChart.png");
            ChartUtilities.saveChartAsJPEG(file1, barChart, 600, 400);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
  String rsa = "RSA";
      String mrea = "MREA";
     String jns = "JNS";
    String one = "1 Kb";
      String two = "2 Kb";
      String three = "3 Kb";
       String four = "4 Kb";
 String five = "5 Kb";
       String six = "6 Kb";
       String seven = "7 Kb";
       String eight = "8 Kb";
       
      DefaultCategoryDataset dataset = new DefaultCategoryDataset( );

      dataset.addValue( 124.0 , rsa , one );
      dataset.addValue( 131.0 , rsa , two );
      dataset.addValue( 137.0 , rsa , three );
      dataset.addValue( 145.0 , rsa , four );
      dataset.addValue( 151.0 , rsa , five );
      dataset.addValue( 159.0 , rsa , six );
      dataset.addValue( 164.0 , rsa , seven );
      dataset.addValue( 172.0 , rsa , eight );

      dataset.addValue( 370.0 , mrea , one );
      dataset.addValue( 391.0 , mrea ,two );
      dataset.addValue( 398.0 , mrea , three );
      dataset.addValue( 409.0 , mrea , four );
       dataset.addValue( 416.0 , mrea , five );
      dataset.addValue( 424.0 , mrea , six );
      dataset.addValue( 431.0 , mrea , seven );
      dataset.addValue( 439.0 , mrea , eight );

      dataset.addValue( 140.0 , jns , one );
      dataset.addValue( 143.0 , jns , two );
      dataset.addValue( 148.0 , jns , three );
      dataset.addValue( 156.0 , jns , four );
       dataset.addValue( 159.0 , jns , five );
        dataset.addValue( 165.0 , jns , six );
         dataset.addValue( 172.0 , jns , seven );
          dataset.addValue( 180.0 , jns , eight );

      JFreeChart barChart = ChartFactory.createBarChart(
         "Decryption Comparison", 
         "Algorithm", "Time", 
         dataset,PlotOrientation.VERTICAL, 
         true, true, false);
          ChartFrame frame1=new ChartFrame("Comparison Between Algorithms",barChart);
        frame1.setVisible(true);
        frame1.setSize(950,450);
      int width = 640; /* Width of the image */
      int height = 480; /* Height of the image */ 
      try{
            final ChartRenderingInfo info= new ChartRenderingInfo(new StandardEntityCollection());
            final File file1=new File("DecryptionKBChart.png");
            ChartUtilities.saveChartAsJPEG(file1, barChart, 600, 400);
        }catch(Exception e){}
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
jTextField1.setText("");  
jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
         jTextField7.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
    public long ETime1=0,DTime1=0;public long ETime2=0,DTime2=0;   
    public long ETime3=0,DTime3=0;    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
